# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46ad2adadc2030f7f8ab9460a28ee7c73c5d51a288398a4bbc575960e94c25a614ed338921d33842fed73c8f1c2fc561f03800b62050fea8ad66f27e00893b49

test:
  secret_key_base: 40622520f535d541bbcfab224a41d124afff326d85ca375c6c8d321fdc3830ba391fce2edb809ea92b669d8ef71f83481348edd241e87d9d6696306f504d32b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
