# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 766a3112b3366d25d8b2a0f425b2ecbc0fc77723753cb359903eb57fe4a8860d920cdd89e57874b4ec04274b294366853b4ddef60aeb456f4fd02c1deaab37b2

test:
  secret_key_base: 85100293a8f13179864fc98efb5cba50fa8fee85f440ebfcfff1cf4c542c191a40ec93c016fb2687e2ef50b937c2de299b09415bb20459b721410494ccfa01f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
